import { t } from 'intlayer';
import type { Dictionary } from 'intlayer';

export default {
  key: "faqs",
  content: {
    faqs: [
      { question: t({ en: "Do I need motion design experience?", es: "¿Necesito experiencia en diseño de movimiento?", fr: "Ai-je besoin d’expérience en motion design ?" }), answer: t({ en: "No. The skills carry the motion knowledge: easing, overlap, holds, and pacing. You describe the result in plain words and review a storyboard before anything is rendered.", es: "No. Las habilidades aportan los conocimientos de movimiento: aceleración, superposición, pausas y ritmo. Describes el resultado con palabras sencillas y revisas un guion gráfico antes de renderizar nada.", fr: "Non. Les compétences apportent le savoir du mouvement : accélération, chevauchements, pauses et rythme. Vous décrivez le résultat en mots simples et examinez un storyboard avant tout rendu." }) },
      { question: t({ en: "What kind of videos can I make?", es: "¿Qué tipo de vídeos puedo crear?", fr: "Quels types de vidéos puis-je créer ?" }), answer: t({ en: "Anything built from motion and type: portfolio showreels, intros, title sequences, launch films, and feature updates.", es: "Todo lo basado en movimiento y tipografía: reels de portafolio, intros, secuencias de títulos, vídeos de lanzamiento y novedades de funciones.", fr: "Tout ce qui repose sur le mouvement et la typographie : bandes démo de portfolio, intros, génériques, films de lancement et nouveautés produit." }) },
      { question: t({ en: "Which coding agents are supported?", es: "¿Qué agentes de programación son compatibles?", fr: "Quels agents de programmation sont compatibles ?" }), answer: t({ en: "Any agent that can read instruction files from your repository, including Claude Code, Codex, Cursor, Antigravity, and GitHub Copilot.", es: "Cualquier agente que pueda leer archivos de instrucciones de tu repositorio, incluidos Claude Code, Codex, Cursor, Antigravity y GitHub Copilot.", fr: "Tout agent capable de lire les fichiers d’instructions de votre dépôt, notamment Claude Code, Codex, Cursor, Antigravity et GitHub Copilot." }) },
      { question: t({ en: "Which renderer should I pick?", es: "¿Qué motor de renderizado debo elegir?", fr: "Quel moteur de rendu choisir ?" }), answer: t({ en: "Use whichever fits your project. Remotion suits React codebases, HyperFrames and Editframe work from HTML, and fframes renders on the GPU. Check each renderer’s own license for commercial use.", es: "Usa el que encaje con tu proyecto. Remotion es adecuado para React, HyperFrames y Editframe trabajan con HTML, y fframes renderiza en la GPU. Consulta la licencia de cada motor para el uso comercial.", fr: "Choisissez celui qui convient à votre projet. Remotion convient à React, HyperFrames et Editframe utilisent HTML, et fframes effectue le rendu sur GPU. Consultez la licence de chaque moteur pour un usage commercial." }) },
      { question: t({ en: "How do I get the files after paying?", es: "¿Cómo obtengo los archivos después de pagar?", fr: "Comment obtenir les fichiers après le paiement ?" }), answer: t({ en: "Checkout needs no account. Right after paying, sign in with the email you paid with, open the Polar customer portal from your dashboard, and link a GitHub account to claim repository access.", es: "No necesitas una cuenta para pagar. Después de pagar, inicia sesión con el correo que usaste, abre el portal de clientes de Polar desde tu panel y vincula una cuenta de GitHub para obtener acceso al repositorio.", fr: "Aucun compte n’est nécessaire pour payer. Après le paiement, connectez-vous avec l’e-mail utilisé, ouvrez le portail client Polar depuis votre tableau de bord et associez un compte GitHub pour obtenir l’accès au dépôt." }) },
      { question: t({ en: "Can I use it for client projects?", es: "¿Puedo usarlo para proyectos de clientes?", fr: "Puis-je l’utiliser pour des projets clients ?" }), answer: t({ en: "Yes. The license is per person and covers every project you work on, including work for clients.", es: "Sí. La licencia es por persona y cubre todos tus proyectos, incluidos los trabajos para clientes.", fr: "Oui. La licence est individuelle et couvre tous vos projets, y compris ceux réalisés pour des clients." }) },
      { question: t({ en: "Can I get a refund?", es: "¿Puedo obtener un reembolso?", fr: "Puis-je obtenir un remboursement ?" }), answer: t({ en: "Yes. Email us before you claim repository access for a full refund. After that, see our refund policy if you have a problem with your order or access.", es: "Sí. Escríbenos antes de solicitar acceso al repositorio para recibir un reembolso completo. Después, consulta nuestra política de reembolsos si tienes algún problema con tu pedido o acceso.", fr: "Oui. Écrivez-nous avant de demander l’accès au dépôt pour obtenir un remboursement intégral. Ensuite, consultez notre politique de remboursement en cas de problème avec votre commande ou votre accès." }) },
    ],
  },
} satisfies Dictionary;
