/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GalleryRouteImport } from './routes/_gallery'
import { Route as PagesRouteImport } from './routes/_pages'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CreativesRouteImport } from './routes/creatives'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExtrasRouteImport } from './routes/extras'
import { Route as MotionvideoSkillRouteImport } from './routes/motionvideo-skill'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SponsorRouteImport } from './routes/sponsor'
import { Route as StudiosRouteImport } from './routes/studios'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as GalleryIndexRouteImport } from './routes/_gallery/index'
import { Route as PagesAboutRouteImport } from './routes/_pages/about'
import { Route as PagesBrandRouteImport } from './routes/_pages/brand'
import { Route as PagesContactRouteImport } from './routes/_pages/contact'
import { Route as PagesDpaRouteImport } from './routes/_pages/dpa'
import { Route as PagesPrivacyRouteImport } from './routes/_pages/privacy'
import { Route as PagesRefundsRouteImport } from './routes/_pages/refunds'
import { Route as PagesTermsRouteImport } from './routes/_pages/terms'
import { Route as CreativesIndexRouteImport } from './routes/creatives/index'
import { Route as CreativesCategoryRouteImport } from './routes/creatives/$category'
import { Route as ExtrasIndexRouteImport } from './routes/extras/index'
import { Route as ExtrasCategoryRouteImport } from './routes/extras/$category'
import { Route as SkillsIndexRouteImport } from './routes/skills/index'
import { Route as SkillsCategoryRouteImport } from './routes/skills/$category'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as ToolsCategoryRouteImport } from './routes/tools/$category'
import { Route as GalleryCategoryCategoryRouteImport } from './routes/_gallery/category.$category'
import { Route as GalleryVideosSlugRouteImport } from './routes/_gallery/videos.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiWebhookDodoRouteImport } from './routes/api/webhook/dodo'
import { Route as GalleryCategoryCategoryIndexRouteImport } from './routes/_gallery/category.$category.index'
import { Route as GalleryCategoryCategoryVideosSlugRouteImport } from './routes/_gallery/category.$category.videos.$slug'

const GalleryRoute = GalleryRouteImport.update({
  id: '/_gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesRoute = PagesRouteImport.update({
  id: '/_pages',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CreativesRoute = CreativesRouteImport.update({
  id: '/creatives',
  path: '/creatives',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtrasRoute = ExtrasRouteImport.update({
  id: '/extras',
  path: '/extras',
  getParentRoute: () => rootRouteImport,
} as any)
const MotionvideoSkillRoute = MotionvideoSkillRouteImport.update({
  id: '/motionvideo-skill',
  path: '/motionvideo-skill',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorRoute = SponsorRouteImport.update({
  id: '/sponsor',
  path: '/sponsor',
  getParentRoute: () => rootRouteImport,
} as any)
const StudiosRoute = StudiosRouteImport.update({
  id: '/studios',
  path: '/studios',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GalleryRoute,
} as any)
const PagesAboutRoute = PagesAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PagesRoute,
} as any)
const PagesBrandRoute = PagesBrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => PagesRoute,
} as any)
const PagesContactRoute = PagesContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PagesRoute,
} as any)
const PagesDpaRoute = PagesDpaRouteImport.update({
  id: '/dpa',
  path: '/dpa',
  getParentRoute: () => PagesRoute,
} as any)
const PagesPrivacyRoute = PagesPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PagesRoute,
} as any)
const PagesRefundsRoute = PagesRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => PagesRoute,
} as any)
const PagesTermsRoute = PagesTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PagesRoute,
} as any)
const CreativesIndexRoute = CreativesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreativesRoute,
} as any)
const CreativesCategoryRoute = CreativesCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => CreativesRoute,
} as any)
const ExtrasIndexRoute = ExtrasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExtrasRoute,
} as any)
const ExtrasCategoryRoute = ExtrasCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => ExtrasRoute,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SkillsRoute,
} as any)
const SkillsCategoryRoute = SkillsCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => SkillsRoute,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsCategoryRoute = ToolsCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => ToolsRoute,
} as any)
const GalleryCategoryCategoryRoute = GalleryCategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => GalleryRoute,
} as any)
const GalleryVideosSlugRoute = GalleryVideosSlugRouteImport.update({
  id: '/videos/$slug',
  path: '/videos/$slug',
  getParentRoute: () => GalleryRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookDodoRoute = ApiWebhookDodoRouteImport.update({
  id: '/api/webhook/dodo',
  path: '/api/webhook/dodo',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryCategoryCategoryIndexRoute =
  GalleryCategoryCategoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => GalleryCategoryCategoryRoute,
  } as any)
const GalleryCategoryCategoryVideosSlugRoute =
  GalleryCategoryCategoryVideosSlugRouteImport.update({
    id: '/videos/$slug',
    path: '/videos/$slug',
    getParentRoute: () => GalleryCategoryCategoryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof GalleryIndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/checkout': typeof CheckoutRoute
  '/creatives': typeof CreativesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/extras': typeof ExtrasRouteWithChildren
  '/motionvideo-skill': typeof MotionvideoSkillRoute
  '/sign-in': typeof SignInRoute
  '/skills': typeof SkillsRouteWithChildren
  '/sponsor': typeof SponsorRoute
  '/studios': typeof StudiosRoute
  '/submit': typeof SubmitRoute
  '/tools': typeof ToolsRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/about': typeof PagesAboutRoute
  '/brand': typeof PagesBrandRoute
  '/contact': typeof PagesContactRoute
  '/dpa': typeof PagesDpaRoute
  '/privacy': typeof PagesPrivacyRoute
  '/refunds': typeof PagesRefundsRoute
  '/terms': typeof PagesTermsRoute
  '/creatives/$category': typeof CreativesCategoryRoute
  '/extras/$category': typeof ExtrasCategoryRoute
  '/skills/$category': typeof SkillsCategoryRoute
  '/tools/$category': typeof ToolsCategoryRoute
  '/creatives/': typeof CreativesIndexRoute
  '/extras/': typeof ExtrasIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/category/$category': typeof GalleryCategoryCategoryRouteWithChildren
  '/videos/$slug': typeof GalleryVideosSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhook/dodo': typeof ApiWebhookDodoRoute
  '/category/$category/': typeof GalleryCategoryCategoryIndexRoute
  '/category/$category/videos/$slug': typeof GalleryCategoryCategoryVideosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof GalleryIndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/motionvideo-skill': typeof MotionvideoSkillRoute
  '/sign-in': typeof SignInRoute
  '/sponsor': typeof SponsorRoute
  '/studios': typeof StudiosRoute
  '/submit': typeof SubmitRoute
  '/welcome': typeof WelcomeRoute
  '/about': typeof PagesAboutRoute
  '/brand': typeof PagesBrandRoute
  '/contact': typeof PagesContactRoute
  '/dpa': typeof PagesDpaRoute
  '/privacy': typeof PagesPrivacyRoute
  '/refunds': typeof PagesRefundsRoute
  '/terms': typeof PagesTermsRoute
  '/creatives/$category': typeof CreativesCategoryRoute
  '/extras/$category': typeof ExtrasCategoryRoute
  '/skills/$category': typeof SkillsCategoryRoute
  '/tools/$category': typeof ToolsCategoryRoute
  '/creatives': typeof CreativesIndexRoute
  '/extras': typeof ExtrasIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/videos/$slug': typeof GalleryVideosSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhook/dodo': typeof ApiWebhookDodoRoute
  '/category/$category': typeof GalleryCategoryCategoryIndexRoute
  '/category/$category/videos/$slug': typeof GalleryCategoryCategoryVideosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_gallery': typeof GalleryRouteWithChildren
  '/_pages': typeof PagesRouteWithChildren
  '/bookmarks': typeof BookmarksRoute
  '/checkout': typeof CheckoutRoute
  '/creatives': typeof CreativesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/extras': typeof ExtrasRouteWithChildren
  '/motionvideo-skill': typeof MotionvideoSkillRoute
  '/sign-in': typeof SignInRoute
  '/skills': typeof SkillsRouteWithChildren
  '/sponsor': typeof SponsorRoute
  '/studios': typeof StudiosRoute
  '/submit': typeof SubmitRoute
  '/tools': typeof ToolsRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/_pages/about': typeof PagesAboutRoute
  '/_pages/brand': typeof PagesBrandRoute
  '/_pages/contact': typeof PagesContactRoute
  '/_pages/dpa': typeof PagesDpaRoute
  '/_pages/privacy': typeof PagesPrivacyRoute
  '/_pages/refunds': typeof PagesRefundsRoute
  '/_pages/terms': typeof PagesTermsRoute
  '/creatives/$category': typeof CreativesCategoryRoute
  '/extras/$category': typeof ExtrasCategoryRoute
  '/skills/$category': typeof SkillsCategoryRoute
  '/tools/$category': typeof ToolsCategoryRoute
  '/_gallery/': typeof GalleryIndexRoute
  '/creatives/': typeof CreativesIndexRoute
  '/extras/': typeof ExtrasIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/_gallery/category/$category': typeof GalleryCategoryCategoryRouteWithChildren
  '/_gallery/videos/$slug': typeof GalleryVideosSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhook/dodo': typeof ApiWebhookDodoRoute
  '/_gallery/category/$category/': typeof GalleryCategoryCategoryIndexRoute
  '/_gallery/category/$category/videos/$slug': typeof GalleryCategoryCategoryVideosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookmarks'
    | '/checkout'
    | '/creatives'
    | '/dashboard'
    | '/extras'
    | '/motionvideo-skill'
    | '/sign-in'
    | '/skills'
    | '/sponsor'
    | '/studios'
    | '/submit'
    | '/tools'
    | '/welcome'
    | '/about'
    | '/brand'
    | '/contact'
    | '/dpa'
    | '/privacy'
    | '/refunds'
    | '/terms'
    | '/creatives/$category'
    | '/extras/$category'
    | '/skills/$category'
    | '/tools/$category'
    | '/creatives/'
    | '/extras/'
    | '/skills/'
    | '/tools/'
    | '/category/$category'
    | '/videos/$slug'
    | '/api/auth/$'
    | '/api/webhook/dodo'
    | '/category/$category/'
    | '/category/$category/videos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookmarks'
    | '/checkout'
    | '/dashboard'
    | '/motionvideo-skill'
    | '/sign-in'
    | '/sponsor'
    | '/studios'
    | '/submit'
    | '/welcome'
    | '/about'
    | '/brand'
    | '/contact'
    | '/dpa'
    | '/privacy'
    | '/refunds'
    | '/terms'
    | '/creatives/$category'
    | '/extras/$category'
    | '/skills/$category'
    | '/tools/$category'
    | '/creatives'
    | '/extras'
    | '/skills'
    | '/tools'
    | '/videos/$slug'
    | '/api/auth/$'
    | '/api/webhook/dodo'
    | '/category/$category'
    | '/category/$category/videos/$slug'
  id:
    | '__root__'
    | '/_gallery'
    | '/_pages'
    | '/bookmarks'
    | '/checkout'
    | '/creatives'
    | '/dashboard'
    | '/extras'
    | '/motionvideo-skill'
    | '/sign-in'
    | '/skills'
    | '/sponsor'
    | '/studios'
    | '/submit'
    | '/tools'
    | '/welcome'
    | '/_pages/about'
    | '/_pages/brand'
    | '/_pages/contact'
    | '/_pages/dpa'
    | '/_pages/privacy'
    | '/_pages/refunds'
    | '/_pages/terms'
    | '/creatives/$category'
    | '/extras/$category'
    | '/skills/$category'
    | '/tools/$category'
    | '/_gallery/'
    | '/creatives/'
    | '/extras/'
    | '/skills/'
    | '/tools/'
    | '/_gallery/category/$category'
    | '/_gallery/videos/$slug'
    | '/api/auth/$'
    | '/api/webhook/dodo'
    | '/_gallery/category/$category/'
    | '/_gallery/category/$category/videos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GalleryRoute: typeof GalleryRouteWithChildren
  PagesRoute: typeof PagesRouteWithChildren
  BookmarksRoute: typeof BookmarksRoute
  CheckoutRoute: typeof CheckoutRoute
  CreativesRoute: typeof CreativesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ExtrasRoute: typeof ExtrasRouteWithChildren
  MotionvideoSkillRoute: typeof MotionvideoSkillRoute
  SignInRoute: typeof SignInRoute
  SkillsRoute: typeof SkillsRouteWithChildren
  SponsorRoute: typeof SponsorRoute
  StudiosRoute: typeof StudiosRoute
  SubmitRoute: typeof SubmitRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  WelcomeRoute: typeof WelcomeRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiWebhookDodoRoute: typeof ApiWebhookDodoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_gallery': {
      id: '/_gallery'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages': {
      id: '/_pages'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creatives': {
      id: '/creatives'
      path: '/creatives'
      fullPath: '/creatives'
      preLoaderRoute: typeof CreativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extras': {
      id: '/extras'
      path: '/extras'
      fullPath: '/extras'
      preLoaderRoute: typeof ExtrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motionvideo-skill': {
      id: '/motionvideo-skill'
      path: '/motionvideo-skill'
      fullPath: '/motionvideo-skill'
      preLoaderRoute: typeof MotionvideoSkillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsor': {
      id: '/sponsor'
      path: '/sponsor'
      fullPath: '/sponsor'
      preLoaderRoute: typeof SponsorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studios': {
      id: '/studios'
      path: '/studios'
      fullPath: '/studios'
      preLoaderRoute: typeof StudiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_gallery/': {
      id: '/_gallery/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof GalleryRoute
    }
    '/_pages/about': {
      id: '/_pages/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PagesAboutRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/brand': {
      id: '/_pages/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof PagesBrandRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/contact': {
      id: '/_pages/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PagesContactRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/dpa': {
      id: '/_pages/dpa'
      path: '/dpa'
      fullPath: '/dpa'
      preLoaderRoute: typeof PagesDpaRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/privacy': {
      id: '/_pages/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PagesPrivacyRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/refunds': {
      id: '/_pages/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof PagesRefundsRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/terms': {
      id: '/_pages/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PagesTermsRouteImport
      parentRoute: typeof PagesRoute
    }
    '/creatives/': {
      id: '/creatives/'
      path: '/'
      fullPath: '/creatives/'
      preLoaderRoute: typeof CreativesIndexRouteImport
      parentRoute: typeof CreativesRoute
    }
    '/creatives/$category': {
      id: '/creatives/$category'
      path: '/$category'
      fullPath: '/creatives/$category'
      preLoaderRoute: typeof CreativesCategoryRouteImport
      parentRoute: typeof CreativesRoute
    }
    '/extras/': {
      id: '/extras/'
      path: '/'
      fullPath: '/extras/'
      preLoaderRoute: typeof ExtrasIndexRouteImport
      parentRoute: typeof ExtrasRoute
    }
    '/extras/$category': {
      id: '/extras/$category'
      path: '/$category'
      fullPath: '/extras/$category'
      preLoaderRoute: typeof ExtrasCategoryRouteImport
      parentRoute: typeof ExtrasRoute
    }
    '/skills/': {
      id: '/skills/'
      path: '/'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof SkillsRoute
    }
    '/skills/$category': {
      id: '/skills/$category'
      path: '/$category'
      fullPath: '/skills/$category'
      preLoaderRoute: typeof SkillsCategoryRouteImport
      parentRoute: typeof SkillsRoute
    }
    '/tools/': {
      id: '/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/$category': {
      id: '/tools/$category'
      path: '/$category'
      fullPath: '/tools/$category'
      preLoaderRoute: typeof ToolsCategoryRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/_gallery/category/$category': {
      id: '/_gallery/category/$category'
      path: '/category/$category'
      fullPath: '/category/$category'
      preLoaderRoute: typeof GalleryCategoryCategoryRouteImport
      parentRoute: typeof GalleryRoute
    }
    '/_gallery/videos/$slug': {
      id: '/_gallery/videos/$slug'
      path: '/videos/$slug'
      fullPath: '/videos/$slug'
      preLoaderRoute: typeof GalleryVideosSlugRouteImport
      parentRoute: typeof GalleryRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook/dodo': {
      id: '/api/webhook/dodo'
      path: '/api/webhook/dodo'
      fullPath: '/api/webhook/dodo'
      preLoaderRoute: typeof ApiWebhookDodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_gallery/category/$category/': {
      id: '/_gallery/category/$category/'
      path: '/'
      fullPath: '/category/$category/'
      preLoaderRoute: typeof GalleryCategoryCategoryIndexRouteImport
      parentRoute: typeof GalleryCategoryCategoryRoute
    }
    '/_gallery/category/$category/videos/$slug': {
      id: '/_gallery/category/$category/videos/$slug'
      path: '/videos/$slug'
      fullPath: '/category/$category/videos/$slug'
      preLoaderRoute: typeof GalleryCategoryCategoryVideosSlugRouteImport
      parentRoute: typeof GalleryCategoryCategoryRoute
    }
  }
}

interface GalleryCategoryCategoryRouteChildren {
  GalleryCategoryCategoryIndexRoute: typeof GalleryCategoryCategoryIndexRoute
  GalleryCategoryCategoryVideosSlugRoute: typeof GalleryCategoryCategoryVideosSlugRoute
}

const GalleryCategoryCategoryRouteChildren: GalleryCategoryCategoryRouteChildren =
  {
    GalleryCategoryCategoryIndexRoute: GalleryCategoryCategoryIndexRoute,
    GalleryCategoryCategoryVideosSlugRoute:
      GalleryCategoryCategoryVideosSlugRoute,
  }

const GalleryCategoryCategoryRouteWithChildren =
  GalleryCategoryCategoryRoute._addFileChildren(
    GalleryCategoryCategoryRouteChildren,
  )

interface GalleryRouteChildren {
  GalleryIndexRoute: typeof GalleryIndexRoute
  GalleryCategoryCategoryRoute: typeof GalleryCategoryCategoryRouteWithChildren
  GalleryVideosSlugRoute: typeof GalleryVideosSlugRoute
}

const GalleryRouteChildren: GalleryRouteChildren = {
  GalleryIndexRoute: GalleryIndexRoute,
  GalleryCategoryCategoryRoute: GalleryCategoryCategoryRouteWithChildren,
  GalleryVideosSlugRoute: GalleryVideosSlugRoute,
}

const GalleryRouteWithChildren =
  GalleryRoute._addFileChildren(GalleryRouteChildren)

interface PagesRouteChildren {
  PagesAboutRoute: typeof PagesAboutRoute
  PagesBrandRoute: typeof PagesBrandRoute
  PagesContactRoute: typeof PagesContactRoute
  PagesDpaRoute: typeof PagesDpaRoute
  PagesPrivacyRoute: typeof PagesPrivacyRoute
  PagesRefundsRoute: typeof PagesRefundsRoute
  PagesTermsRoute: typeof PagesTermsRoute
}

const PagesRouteChildren: PagesRouteChildren = {
  PagesAboutRoute: PagesAboutRoute,
  PagesBrandRoute: PagesBrandRoute,
  PagesContactRoute: PagesContactRoute,
  PagesDpaRoute: PagesDpaRoute,
  PagesPrivacyRoute: PagesPrivacyRoute,
  PagesRefundsRoute: PagesRefundsRoute,
  PagesTermsRoute: PagesTermsRoute,
}

const PagesRouteWithChildren = PagesRoute._addFileChildren(PagesRouteChildren)

interface CreativesRouteChildren {
  CreativesCategoryRoute: typeof CreativesCategoryRoute
  CreativesIndexRoute: typeof CreativesIndexRoute
}

const CreativesRouteChildren: CreativesRouteChildren = {
  CreativesCategoryRoute: CreativesCategoryRoute,
  CreativesIndexRoute: CreativesIndexRoute,
}

const CreativesRouteWithChildren = CreativesRoute._addFileChildren(
  CreativesRouteChildren,
)

interface ExtrasRouteChildren {
  ExtrasCategoryRoute: typeof ExtrasCategoryRoute
  ExtrasIndexRoute: typeof ExtrasIndexRoute
}

const ExtrasRouteChildren: ExtrasRouteChildren = {
  ExtrasCategoryRoute: ExtrasCategoryRoute,
  ExtrasIndexRoute: ExtrasIndexRoute,
}

const ExtrasRouteWithChildren =
  ExtrasRoute._addFileChildren(ExtrasRouteChildren)

interface SkillsRouteChildren {
  SkillsCategoryRoute: typeof SkillsCategoryRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
}

const SkillsRouteChildren: SkillsRouteChildren = {
  SkillsCategoryRoute: SkillsCategoryRoute,
  SkillsIndexRoute: SkillsIndexRoute,
}

const SkillsRouteWithChildren =
  SkillsRoute._addFileChildren(SkillsRouteChildren)

interface ToolsRouteChildren {
  ToolsCategoryRoute: typeof ToolsCategoryRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsCategoryRoute: ToolsCategoryRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  GalleryRoute: GalleryRouteWithChildren,
  PagesRoute: PagesRouteWithChildren,
  BookmarksRoute: BookmarksRoute,
  CheckoutRoute: CheckoutRoute,
  CreativesRoute: CreativesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ExtrasRoute: ExtrasRouteWithChildren,
  MotionvideoSkillRoute: MotionvideoSkillRoute,
  SignInRoute: SignInRoute,
  SkillsRoute: SkillsRouteWithChildren,
  SponsorRoute: SponsorRoute,
  StudiosRoute: StudiosRoute,
  SubmitRoute: SubmitRoute,
  ToolsRoute: ToolsRouteWithChildren,
  WelcomeRoute: WelcomeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiWebhookDodoRoute: ApiWebhookDodoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
